server:
  port: 8082

eureka:
  client:
    #是否需要将自己注册到注册中心
    register-with-eureka: false
    #是否从注册中心获取注册信息
    fetch-registry: true
    #客户端和服务端交互的地址
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
#  instance:
#    prefer-ip-address: true    # 是否将自己的IP地址注册到eureka


spring:
  application:
    name: microservice-order

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

